## Hent data

- BVP dataframes har 64 observationer/sek
- EDA dataframes har 4 observationer/sek
- HR dataframes har 1 observationer/sek
- TEMP dataframes har 4 observationer/sek

### Vi vælger at interpollere og downscale til 16 punkter i sekundet for at beholde mere information fra BVP

- BVP: 64 -> 16 (mean på hvert 4 punkt)
- EDA: 4 -> 16 (interpoler 3 nye punkter mellem hvert punktsæt)
- HR: 1 -> 16 (interpoler 15 nye punkter mellem hvert sekund)
- TEMP: 4 -> 16 (interpoler 15 nye punkter mellem hvert punktsæt)

In [ ]:
import pandas as pd
from datetime import datetime, timedelta

In [113]:
1/16

0.0625

In [130]:
df_BVP = pd.read_csv('/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset/D1_1/ID_1/round_1/phase1/BVP.csv')
df_BVP['time'] = pd.to_datetime(df_BVP['time'], format='mixed')
df_BVP = df_BVP.set_index('time').sort_index()
# OBS: nedenstående sammensætning af data tager et mean på 4 datapunkter ad gangen og sætter denne værdi på den første plads
df_BVP_downsampled = df_BVP.resample("62.5ms").mean()
df_BVP_downsampled[1:17]

                            Unnamed: 0       BVP
time
2021-12-17 16:11:55.000000         4.5  -12.3100
2021-12-17 16:11:55.062500         8.5   26.7025
2021-12-17 16:11:55.125000        12.5   14.4375
2021-12-17 16:11:55.187500        16.5    8.5275
2021-12-17 16:11:55.250000        20.5   23.7950
2021-12-17 16:11:55.312500        24.5   47.9625
2021-12-17 16:11:55.375000        28.5   60.4700
2021-12-17 16:11:55.437500        32.5   60.3075
2021-12-17 16:11:55.500000        36.5   37.3775
2021-12-17 16:11:55.562500        40.5   -6.5650
2021-12-17 16:11:55.625000        44.5  -32.9200
2021-12-17 16:11:55.687500        48.5   92.6950
2021-12-17 16:11:55.750000        52.5  280.7675
2021-12-17 16:11:55.812500        56.5  462.9950
2021-12-17 16:11:55.875000        60.5  668.9850
2021-12-17 16:11:55.937500        64.5  795.4525

In [155]:
len(df_BVP)

28624

In [139]:
df_EDA = pd.read_csv('/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset/D1_1/ID_1/round_1/phase1/EDA.csv')
df_EDA['time'] = pd.to_datetime(df_EDA['time'], format='mixed')
df_EDA = df_EDA.set_index('time').sort_index()
df_EDA_upsampled = df_EDA.resample("62.5ms").asfreq()

# 3. Interpolér de manglende værdier
# 'linear' trækker en ret linje mellem de kendte punkter
df_EDA_upsampled['EDA'] = df_EDA_upsampled['EDA'].interpolate(method='linear')
df_EDA_upsampled[:16]

                            Unnamed: 0       EDA
time
2021-12-17 16:11:55.000000         0.0  0.185827
2021-12-17 16:11:55.062500         NaN  0.190312
2021-12-17 16:11:55.125000         NaN  0.194798
2021-12-17 16:11:55.187500         NaN  0.199283
2021-12-17 16:11:55.250000         1.0  0.203768
2021-12-17 16:11:55.312500         NaN  0.200884
2021-12-17 16:11:55.375000         NaN  0.198001
2021-12-17 16:11:55.437500         NaN  0.195117
2021-12-17 16:11:55.500000         2.0  0.192234
2021-12-17 16:11:55.562500         NaN  0.191593
2021-12-17 16:11:55.625000         NaN  0.190952
2021-12-17 16:11:55.687500         NaN  0.190312
2021-12-17 16:11:55.750000         3.0  0.189671
2021-12-17 16:11:55.812500         NaN  0.188710
2021-12-17 16:11:55.875000         NaN  0.187749
2021-12-17 16:11:55.937500         NaN  0.186788

In [141]:
df_HR = pd.read_csv('/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset/D1_1/ID_1/round_1/phase1/HR.csv')
df_HR['time'] = pd.to_datetime(df_HR['time'], format='mixed')
df_HR = df_HR.set_index('time').sort_index()
df_HR_upsampled = df_HR.resample("62.5ms").asfreq()

# 3. Interpolér de manglende værdier
# 'linear' trækker en ret linje mellem de kendte punkter
df_HR_upsampled['HR'] = df_HR_upsampled['HR'].interpolate(method='linear')
df_HR_upsampled[:16]

                            Unnamed: 0     HR
time
2021-12-17 16:11:55.000000         0.0  76.75
2021-12-17 16:11:55.062500         NaN  76.75
2021-12-17 16:11:55.125000         NaN  76.75
2021-12-17 16:11:55.187500         NaN  76.75
2021-12-17 16:11:55.250000         NaN  76.75
2021-12-17 16:11:55.312500         NaN  76.75
2021-12-17 16:11:55.375000         NaN  76.75
2021-12-17 16:11:55.437500         NaN  76.75
2021-12-17 16:11:55.500000         NaN  76.75
2021-12-17 16:11:55.562500         NaN  76.75
2021-12-17 16:11:55.625000         NaN  76.75
2021-12-17 16:11:55.687500         NaN  76.75
2021-12-17 16:11:55.750000         NaN  76.75
2021-12-17 16:11:55.812500         NaN  76.75
2021-12-17 16:11:55.875000         NaN  76.75
2021-12-17 16:11:55.937500         NaN  76.75
2021-12-17 16:11:56.000000         1.0  76.75

In [143]:
df_TEMP = pd.read_csv('/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset/D1_1/ID_1/round_1/phase1/TEMP.csv')
df_TEMP['time'] = pd.to_datetime(df_TEMP['time'], format='mixed')
df_TEMP = df_TEMP.set_index('time').sort_index()
df_TEMP_upsampled = df_TEMP.resample("62.5ms").asfreq()

# 3. Interpolér de manglende værdier
# 'linear' trækker en ret linje mellem de kendte punkter
df_TEMP_upsampled['TEMP'] = df_TEMP_upsampled['TEMP'].interpolate(method='linear')
df_TEMP_upsampled[:16]

                            Unnamed: 0   TEMP
time
2021-12-17 16:11:55.000000         0.0  30.97
2021-12-17 16:11:55.062500         NaN  30.97
2021-12-17 16:11:55.125000         NaN  30.97
2021-12-17 16:11:55.187500         NaN  30.97
2021-12-17 16:11:55.250000         1.0  30.97
2021-12-17 16:11:55.312500         NaN  30.97
2021-12-17 16:11:55.375000         NaN  30.97
2021-12-17 16:11:55.437500         NaN  30.97
2021-12-17 16:11:55.500000         2.0  30.97
2021-12-17 16:11:55.562500         NaN  30.97
2021-12-17 16:11:55.625000         NaN  30.97
2021-12-17 16:11:55.687500         NaN  30.97
2021-12-17 16:11:55.750000         3.0  30.97
2021-12-17 16:11:55.812500         NaN  30.98
2021-12-17 16:11:55.875000         NaN  30.99
2021-12-17 16:11:55.937500         NaN  31.00

In [156]:
dfs_to_combine = [df_BVP_downsampled[['BVP']], df_EDA_upsampled[['EDA']], df_HR_upsampled[['HR']], df_TEMP_upsampled[['TEMP']]]

Collected_dataframes = pd.concat(dfs_to_combine, axis=1, join='inner')

Collected_dataframes = Collected_dataframes.reset_index()
Collected_dataframes.head(20)

                         time       BVP       EDA        HR   TEMP
0  2021-12-17 16:11:55.000000  -12.3100  0.185827  76.75000  30.97
1  2021-12-17 16:11:55.062500   26.7025  0.190312  76.75000  30.97
2  2021-12-17 16:11:55.125000   14.4375  0.194798  76.75000  30.97
3  2021-12-17 16:11:55.187500    8.5275  0.199283  76.75000  30.97
4  2021-12-17 16:11:55.250000   23.7950  0.203768  76.75000  30.97
5  2021-12-17 16:11:55.312500   47.9625  0.200884  76.75000  30.97
6  2021-12-17 16:11:55.375000   60.4700  0.198001  76.75000  30.97
7  2021-12-17 16:11:55.437500   60.3075  0.195117  76.75000  30.97
8  2021-12-17 16:11:55.500000   37.3775  0.192234  76.75000  30.97
9  2021-12-17 16:11:55.562500   -6.5650  0.191593  76.75000  30.97
10 2021-12-17 16:11:55.625000  -32.9200  0.190952  76.75000  30.97
11 2021-12-17 16:11:55.687500   92.6950  0.190312  76.75000  30.97
12 2021-12-17 16:11:55.750000  280.7675  0.189671  76.75000  30.97
13 2021-12-17 16:11:55.812500  462.9950  0.188710  76.75000  30.98
14 2021-12-17 16:11:55.875000  668.9850  0.187749  76.75000  30.99
15 2021-12-17 16:11:55.937500  795.4525  0.186788  76.75000  31.00
16 2021-12-17 16:11:56.000000  909.6050  0.185827  76.75000  31.01
17 2021-12-17 16:11:56.062500  581.5025  0.185506  76.74875  31.01
18 2021-12-17 16:11:56.125000 -334.4850  0.185186  76.74750  31.01
19 2021-12-17 16:11:56.187500 -891.2900  0.184865  76.74625  31.01

In [188]:
def prepare_dataframe(path_to_phase, file):
    colname = file.split('.')[0]
    df = pd.read_csv(path_to_phase+ file)
    df['time'] = pd.to_datetime(df['time'], format='mixed')
    df = df.set_index('time').sort_index()

    if file== 'BVP.csv':
        df_downsampled = df.resample("62.5ms").mean()
        return df_downsampled[[colname]]
    else: 
        #sæt en interpoleringsfrekvens på 62.5 ms som svarer til 1/16 sekund og interpoler
        df_upsampled = df.resample("62.5ms").asfreq()
        df_upsampled[colname] = df_upsampled[colname].interpolate(method='linear')
        return df_upsampled[[colname]]
    
    
def create_phase_dataframe(path_to_phase):
    filenames = ['BVP.csv', 'EDA.csv', 'HR.csv', 'TEMP.csv']
    dfs_to_combine = []
    for file in filenames:
        df = prepare_dataframe(path_to_phase, file)
        dfs_to_combine.append(df)
    
    Collected_dataframes = pd.concat(dfs_to_combine, axis=1, join='inner')

    # 3. Hvis du gerne vil have 'time' tilbage som en almindelig kolonne til sidst:
    Collected_dataframes = Collected_dataframes.reset_index()
    return Collected_dataframes
        

path_phase = '/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset/D1_1/ID_1/round_1/phase1/'

phase_dataframe = create_phase_dataframe(path_phase)
phase_dataframe.tail()

                           time       BVP       EDA         HR    TEMP
7148 2021-12-17 16:19:21.750000  -88.9000  0.287070  78.852500  31.450
7149 2021-12-17 16:19:21.812500 -162.2075  0.286749  78.856875  31.455
7150 2021-12-17 16:19:21.875000 -139.4200  0.286429  78.861250  31.460
7151 2021-12-17 16:19:21.937500  -73.7275  0.286108  78.865625  31.465
7152 2021-12-17 16:19:22.000000  -41.0475  0.285788  78.870000  31.470

In [173]:
path_phase2 = '/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset/D1_1/ID_1/round_1/phase2/'

phase_dataframe2 = create_phase_dataframe(path_phase2)
phase_dataframe2.head()

                        time       BVP       EDA         HR   TEMP
0 2021-12-17 16:24:09.000000 -134.8000  0.367808  99.050000  32.29
1 2021-12-17 16:24:09.062500 -158.4975  0.367808  99.045625  32.29
2 2021-12-17 16:24:09.125000 -162.2650  0.367808  99.041250  32.29
3 2021-12-17 16:24:09.187500 -126.3600  0.367808  99.036875  32.29
4 2021-12-17 16:24:09.250000  -27.9300  0.367808  99.032500  32.29

In [190]:
len(phase_dataframe),len(phase_dataframe2)

(7153, 6257)

In [ ]:
phase_dataframe2['TEMP']

In [191]:
7000*3*4

84000

In [11]:
import pandas as pd
import pathlib
import os

# Definer stien
dataset_path = r'/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset'

alle_data = []

# 1. Loop: Grupper
for gruppe in os.listdir(dataset_path):
    gruppe_sti = os.path.join(dataset_path, gruppe)
    print(gruppe)
    if not os.path.isdir(gruppe_sti): continue
    
    # 2. Loop: Personer
    for person in os.listdir(gruppe_sti):
        person_sti = os.path.join(gruppe_sti, person)

        if not os.path.isdir(person_sti): continue
        
        # 3. Loop: Runder
        for runde in os.listdir(person_sti):
            runde_sti = os.path.join(person_sti, runde)
            if not os.path.isdir(runde_sti): continue
            
            # 4. Loop: Phaser
            for phase in os.listdir(runde_sti):
                phase_sti = os.path.join(runde_sti, phase)
                if not os.path.isdir(phase_sti): continue
                
                # Nu er vi nede ved filerne i den specifikke phase
                for filnavn in os.listdir(phase_sti):
                    if filnavn.endswith('.csv'):
                        fuld_sti = os.path.join(phase_sti, filnavn)
                        
                        # Indlæs data
                        df = pd.read_csv(fuld_sti)
                        
                        # Tilføj metadata så du ved hvor rækkerne stammer fra
                        df['Gruppe'] = gruppe
                        df['Person'] = person
                        df['Runde'] = runde
                        df['Phase'] = phase
                        df['Filnavn'] = filnavn
                        
                        alle_data.append(df)
                        #print(f"Indlæst: {gruppe} > {person} > {runde} > {phase} > {filnavn}")

D1_1
D1_6
D1_3
D1_4
D1_5
D1_2

In [179]:
dataset_path = r'/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset'
for i,Day in enumerate(os.listdir(dataset_path)):
    print(i,gruppe)

0 D1_2
1 D1_2
2 D1_2
3 D1_2
4 D1_2
5 D1_2

In [ ]:
dataset_path = r'/Users/mathildenielsen/Desktop/02582_CDA/Case2/biosignal-analysis/data/raw/dataset'
Days = os.listdir(dataset_path)
print(Days)





for i, Day in enumerate(os.listdir(dataset_path)):
    print(i,Day)

['D1_1', 'D1_6', 'D1_3', 'D1_4', 'D1_5', 'D1_2']
0 D1_1
1 D1_6
2 D1_3
3 D1_4
4 D1_5
5 D1_2

In [181]:
os.listdir(dataset_path)

['D1_1', 'D1_6', 'D1_3', 'D1_4', 'D1_5', 'D1_2']

In [174]:
dict1 = {}

for i in range(10):
    dict1[f"Agens phase {i}"] = 10


dict1

{'Agens phase 0': 10,
 'Agens phase 1': 10,
 'Agens phase 2': 10,
 'Agens phase 3': 10,
 'Agens phase 4': 10,
 'Agens phase 5': 10,
 'Agens phase 6': 10,
 'Agens phase 7': 10,
 'Agens phase 8': 10,
 'Agens phase 9': 10}